spring.application.name=attacksimulator

# =========================
# MySQL
# =========================

spring.datasource.url=jdbc:mysql://localhost:3306/newauthlab?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Webサーバーを起動しない
spring.main.web-application-type=none